### ISSUE TITLE
Unable to start up on OS X

### ISSUE THREAD

**Issue by sstrang** [JohnDoee/spreadsheetui#2]
This project looks awesome! I'm having difficulties running it, unfortunately.

```user:spreadsheetui user$ env/bin/twistd spreadsheetui
/Users/user/spreadsheetui/env/lib/python3.7/site-packages/environ/environ.py:639: UserWarning: Error reading .env - if you're not configuring your environment separately, check this.
  "environment separately, check this." % env_file)
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions, spreadsheetui
Running migrations:
  No migrations to apply.

0 static files copied to '/Users/user/spreadsheetui/static', 201 unmodified. 
```

I seem to be getting the same error running it from the virtual environment and from docker. Any suggested resolution? I don't know enough about the python ecosystem to know how to quickly fix it.

Edit: I guess I should note that I'm running this on OS X rather than Linux - perhaps that's my problem

Edit2: here's a stack trace from twistd.log:

```
2020-06-07T16:31:20+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/base.py", line 434, in fireEvent
            DeferredList(beforeResults).addCallback(self._continueFiring)
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 322, in addCallback
            callbackKeywords=kw)
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 311, in addCallbacks
            self._runCallbacks()
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
        --- <exception caught here> ---
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/base.py", line 447, in _continueFiring
            callable(*args, **kwargs)
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/base.py", line 1278, in _reallyStartRunning
            self._handleSignals()
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/posixbase.py", line 300, in _handleSignals
            self.addReader(self._childWaker)
          File "/Users/user/spreadsheetui/env/lib/python3.7/site-packages/twisted/internet/asyncioreactor.py", line 153, in addReader
            True)
          File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 324, in add_reader
            return self._add_reader(fd, callback, *args)
          File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 254, in _add_reader
            (handle, None))
          File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 522, in register
            self._selector.control([kev], 0, 0)
        builtins.OSError: [Errno 9] Bad file descriptor
```

**Comment by JohnDoee** [comment]
It seems related to Mac OS X - I found another ticket with similar problem https://github.com/django/channels/issues/962.

I honestly don't know what to do about it as I got no access to a mac.

**Comment by sstrang** [comment]
I'll sort it out and will post my solution here. Just tried it on a Linux machine and it worked without issue. Thanks for your great work!
