### ISSUE TITLE
Can't connect to qBittorrent

### ISSUE THREAD

**Issue by awcip** [JohnDoee/spreadsheetui#4]
There seems to be some problem connecting to qBittorrent from spreadsheetui. I am using the latest 4.3.8 version from [linuxserver/qbittorrent](https://hub.docker.com/r/linuxserver/qbittorrent).
```
[clients.qbittorrent]
display_name = "qbittorrent"
client_type = "qbittorrent"
url = "http://qbittorrent:8080/"
username = "admin"
password = "adminadmin"
```
I can ping "qbittorrent" since it's on the same docker network as spreadsheeui docker but get an exception like this:
```
| INFO     | twisted.plugins.spreadsheetui_plugin:cycle:109 - qbittorrent Running a full update
[stderr#error] Job "UpdateTorrentClient.cycle (trigger: interval[0:00:02], next run at: <removed> UTC)" raised an exception
[stderr#error] Traceback (most recent call last):
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
[stderr#error]     retval = job.func(*job.args, **job.kwargs)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/twisted/plugins/spreadsheetui_plugin.py", line 110, in cycle
[stderr#error]     update_torrents([self.torrent_client], partial_update=False)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/spreadsheetui/tasks.py", line 92, in update_torrents
[stderr#error]     Torrent.objects.bulk_create(new_torrents)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
[stderr#error]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 493, in bulk_create
[stderr#error]     objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts,
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1223, in _batched_insert
[stderr#error]     ignore_conflicts=ignore_conflicts,
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/query.py", line 1204, in _insert
[stderr#error]     return query.get_compiler(using=using).execute_sql(returning_fields)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1391, in execute_sql
[stderr#error]     for sql, params in self.as_sql():
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1336, in as_sql
[stderr#error]     for obj in self.query.objs
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1336, in <listcomp>
[stderr#error]     for obj in self.query.objs
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in <listcomp>
[stderr#error]     [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1276, in prepare_value
[stderr#error]     value = field.get_db_prep_save(value, connection=self.connection)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 821, in get_db_prep_save
[stderr#error]     return self.get_db_prep_value(value, connection=connection, prepared=False)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1376, in get_db_prep_value
[stderr#error]     value = self.get_prep_value(value)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1355, in get_prep_value
[stderr#error]     value = super().get_prep_value(value)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1215, in get_prep_value
[stderr#error]     return self.to_python(value)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/db/models/fields/__init__.py", line 1316, in to_python
[stderr#error]     parsed = parse_datetime(value)
[stderr#error]   File "/usr/local/lib/python3.7/site-packages/django/utils/dateparse.py", line 107, in parse_datetime
[stderr#error]     match = datetime_re.match(value)
[stderr#error] TypeError: expected string or bytes-like object
```

**Comment by oldsweatyman** [comment]
+1, I am having the same issue, would love to use spreadsheetui with qbit.

**Comment by sage2050** [comment]
same
